name: version_check
description: Check store version and provide update alert.
version: 0.1.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/version_check

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+18
  http: ^0.12.1
  html: ^0.14.0+3
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
